#ifndef MODEL_TYPES_H
#define MODEL_TYPES_H

namespace Model {

enum EnemyType {
    ET_None, ET_Slime, ET_Skel, ET_Bat, ET_Brute, ET_Mage,
    ET_Minion, ET_MiniBoss, ET_FinalBoss
};

enum AnimType { AN_Idle, AN_Walk, AN_Atk, AN_Hurt, AN_Death };

enum GameState {
    GS_Menu, GS_SkinSelect, GS_Discoveries, GS_Lore,
    GS_Tutorial,
    GS_Playing, GS_RoomCleared, GS_FadeOut, GS_SkillSelect, GS_FadeIn,
    GS_GameOver, GS_Victory
};

// Skill IDs - 65 total
enum SkillId {
    SK_DBL=0, SK_TRI, SK_FST, SK_PRC, SK_SPD, SK_POW, SK_BNC, SK_DIA,
    SK_HARDCORE, SK_DODGE, SK_LIGHT_FOOT, SK_RANGE, SK_KNOCKBACK, SK_BIG_ARROW,
    SK_HUNTER, SK_SHARP, SK_FIRST_HIT, SK_FOCUSED,
    SK_GRN,
    SK_LIFESTEAL, SK_NECRO, SK_DEATH_MARK, SK_BONE_SHIELD, SK_BLOOD_PACT,
    SK_REGEN, SK_RESILIENCE, SK_PHOENIX, SK_SOUL_DRAIN, SK_DECAY,
    SK_VAMP_NERFED, SK_FROST_FATE,
    SK_POISON, SK_BLAZE, SK_EXPLODE_KILL, SK_FIRE_TRAIL, SK_DOUBLE_GRENADE,
    SK_BIG_BOOM, SK_VOLCANO, SK_RECKLESS, SK_BURST_FIRE, SK_INFERNO,
    SK_STICKY, SK_GHOST_ARROW,
    SK_DASH, SK_RAM, SK_BERSERKER, SK_HEAVY, SK_THORNS, SK_TANK,
    SK_RAGE_STACK, SK_SHIELD, SK_LAST_HOPE, SK_ADRENALINE, SK_REFLECT, SK_FINISHER,
    SK_FROST_AURA, SK_FREEZE_HIT, SK_ICE_SHARDS, SK_TIME_STOP, SK_LEGEND,
    SK_MASTERY, SK_ECHO, SK_INVUL_BURST, SK_FROST_NOVA, SK_HOMING,
    SK_CRIT_NERFED, SK_QUAD_NERFED,
    SK_SPLT_NERFED, SK_FRZ_NERFED, SK_MAXHP_NERFED,
    SK__COUNT
};

}

#endif
